// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-quaynor.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "QuaynorSpec.h"

@interface Quaynor : NSObject <NativeQuaynorSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Quaynor : NSObject <RCTBridgeModule>
#endif

@end