#ifndef QUAYNOR_REACT_NATIVE_H
#define QUAYNOR_REACT_NATIVE_H
// Generated by uniffi-bindgen-react-native
#include <cstdint>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvoker.h>

namespace quaynorreactnative {
  using namespace facebook;

  uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker);
  uint8_t cleanupRustCrate(jsi::Runtime &runtime);
}

#endif /* QUAYNOR_REACT_NATIVE_H */