// Generated by uniffi-bindgen-react-native
#include "react-native-quaynor.h"
#include "../generated/cpp/quaynor.hpp"

namespace quaynor {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeQuaynor::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}